import type { EvidenceItem } from "./evidence-types";

const REC_DEFAULTS = {
  recommenderName: "",
  recommenderRole: "",
  recommenderIsSenior: null as boolean | null,
  recommenderIsUkBased: null as boolean | null,
  recommenderHasCollaborated: null as boolean | null,
  recommenderCollaborationProject: "",
  recommenderHasCredentials: null as boolean | null,
  recommenderCanUseLetterhead: null as boolean | null,
};

const DONE = "done" as const;
const INTENT = "intent" as const;

export const MOCK_EVIDENCE: EvidenceItem[] = [
  {
    id: "ev-001",
    status: DONE,
    category: "media-recognition",
    title: "Feature interview on contemporary painting practice",
    organisation: "The Guardian",
    country: "United Kingdom",
    date: "2024-09",
    linkOrUpload: "https://example.com/guardian-feature",
    applicantNameVisible: true,
    applicantRoleClear: true,
    workTitleVisible: true,
    wasCuratedOrSelected: null,
    withinLastFiveYears: true,
    hasThirdPartyProof: true,
    sourceAuthority: "national-established",
    notes: "Full-page feature in Arts section. Print and online. Named critic.",
    ...REC_DEFAULTS,
  },
  {
    id: "ev-002",
    status: DONE,
    category: "media-recognition",
    title: "Solo show review in Frieze magazine",
    organisation: "Frieze",
    country: "United Kingdom",
    date: "2023-11",
    linkOrUpload: "https://example.com/frieze-review",
    applicantNameVisible: true,
    applicantRoleClear: true,
    workTitleVisible: true,
    wasCuratedOrSelected: null,
    withinLastFiveYears: true,
    hasThirdPartyProof: true,
    sourceAuthority: "professional-respected",
    notes: "Critical review of solo exhibition. Named critic: J. Smith.",
    ...REC_DEFAULTS,
  },
  {
    id: "ev-003",
    status: DONE,
    category: "media-recognition",
    title: "Blog post by independent curator",
    organisation: "Personal blog",
    country: "Germany",
    date: "2024-03",
    linkOrUpload: "https://example.com/curator-blog",
    applicantNameVisible: true,
    applicantRoleClear: false,
    workTitleVisible: false,
    wasCuratedOrSelected: null,
    withinLastFiveYears: true,
    hasThirdPartyProof: false,
    sourceAuthority: "self-published",
    notes: "Positive but informal. Curator not widely known.",
    ...REC_DEFAULTS,
  },
  {
    id: "ev-004",
    status: DONE,
    category: "prize-nomination",
    title: "Shortlisted for the Max Mara Art Prize for Women",
    organisation: "Whitechapel Gallery / Max Mara",
    country: "United Kingdom",
    date: "2024-06",
    linkOrUpload: "https://example.com/maxmara-shortlist",
    applicantNameVisible: true,
    applicantRoleClear: true,
    workTitleVisible: true,
    wasCuratedOrSelected: true,
    withinLastFiveYears: true,
    hasThirdPartyProof: true,
    sourceAuthority: "international-major",
    notes: "Competitive international prize. Shortlist announced publicly.",
    ...REC_DEFAULTS,
  },
  {
    id: "ev-005",
    status: DONE,
    category: "prize-nomination",
    title: "Winner, local emerging artist award",
    organisation: "City Arts Council",
    country: "Portugal",
    date: "2020-02",
    linkOrUpload: "",
    applicantNameVisible: true,
    applicantRoleClear: true,
    workTitleVisible: false,
    wasCuratedOrSelected: true,
    withinLastFiveYears: false,
    hasThirdPartyProof: false,
    sourceAuthority: "local-regional",
    notes: "Small local prize. No online record remains.",
    ...REC_DEFAULTS,
  },
  {
    id: "ev-006",
    status: DONE,
    category: "exhibition-performance",
    title: "Solo exhibition: Tate Modern Project Space",
    organisation: "Tate Modern",
    country: "United Kingdom",
    date: "2024-01",
    linkOrUpload: "https://example.com/tate-solo",
    applicantNameVisible: true,
    applicantRoleClear: true,
    workTitleVisible: true,
    wasCuratedOrSelected: true,
    withinLastFiveYears: true,
    hasThirdPartyProof: true,
    sourceAuthority: "international-major",
    notes: "3-month solo presentation. Catalogue published.",
    ...REC_DEFAULTS,
  },
  {
    id: "ev-007",
    status: DONE,
    category: "exhibition-performance",
    title: "Group show at Art Basel (Unlimited section)",
    organisation: "Art Basel",
    country: "Switzerland",
    date: "2023-06",
    linkOrUpload: "https://example.com/art-basel",
    applicantNameVisible: true,
    applicantRoleClear: true,
    workTitleVisible: true,
    wasCuratedOrSelected: true,
    withinLastFiveYears: true,
    hasThirdPartyProof: true,
    sourceAuthority: "international-major",
    notes: "Represented by gallery in Unlimited section.",
    ...REC_DEFAULTS,
  },
  {
    id: "ev-008",
    status: DONE,
    category: "exhibition-performance",
    title: "MFA degree show",
    organisation: "University of the Arts London",
    country: "United Kingdom",
    date: "2019-06",
    linkOrUpload: "",
    applicantNameVisible: true,
    applicantRoleClear: true,
    workTitleVisible: true,
    wasCuratedOrSelected: false,
    withinLastFiveYears: false,
    hasThirdPartyProof: false,
    sourceAuthority: "local-regional",
    notes: "Student exhibition. Part of MFA assessment.",
    ...REC_DEFAULTS,
  },
  {
    id: "ev-009",
    status: INTENT,
    category: "exhibition-performance",
    title: "Community art fair table",
    organisation: "Hackney Art Trail",
    country: "United Kingdom",
    date: "2024-07",
    linkOrUpload: "",
    applicantNameVisible: false,
    applicantRoleClear: false,
    workTitleVisible: false,
    wasCuratedOrSelected: false,
    withinLastFiveYears: true,
    hasThirdPartyProof: false,
    sourceAuthority: "local-regional",
    notes: "Open-call community event. No curation or selection.",
    ...REC_DEFAULTS,
  },
  {
    id: "ev-010",
    status: DONE,
    category: "recommendation-letter",
    title: "Letter from Director of Serpentine Galleries",
    organisation: "Serpentine Galleries",
    country: "United Kingdom",
    date: "2024-10",
    linkOrUpload: "",
    applicantNameVisible: true,
    applicantRoleClear: true,
    workTitleVisible: null,
    wasCuratedOrSelected: null,
    withinLastFiveYears: true,
    hasThirdPartyProof: true,
    sourceAuthority: "international-major",
    notes: "Senior figure with international recognition. Has curated applicant twice.",
    recommenderName: "Hans Ulrich Obrist",
    recommenderRole: "Artistic Director",
    recommenderIsSenior: true,
    recommenderIsUkBased: true,
    recommenderHasCollaborated: true,
    recommenderCollaborationProject: "Solo exhibition 2024, group show 2022",
    recommenderHasCredentials: true,
    recommenderCanUseLetterhead: true,
  },
  {
    id: "ev-011",
    status: DONE,
    category: "recommendation-letter",
    title: "Letter from university tutor",
    organisation: "University of the Arts London",
    country: "United Kingdom",
    date: "2024-10",
    linkOrUpload: "",
    applicantNameVisible: true,
    applicantRoleClear: true,
    workTitleVisible: null,
    wasCuratedOrSelected: null,
    withinLastFiveYears: true,
    hasThirdPartyProof: false,
    sourceAuthority: "local-regional",
    notes: "Former MFA tutor. Known within UK academia but limited international profile.",
    recommenderName: "Dr. Sarah Fielding",
    recommenderRole: "Senior Lecturer",
    recommenderIsSenior: false,
    recommenderIsUkBased: true,
    recommenderHasCollaborated: true,
    recommenderCollaborationProject: "MFA thesis supervision 2018-2019",
    recommenderHasCredentials: true,
    recommenderCanUseLetterhead: true,
  },
  {
    id: "ev-012",
    status: DONE,
    category: "recommendation-letter",
    title: "Letter from international collector",
    organisation: "Independent",
    country: "United States",
    date: "2024-09",
    linkOrUpload: "",
    applicantNameVisible: true,
    applicantRoleClear: true,
    workTitleVisible: null,
    wasCuratedOrSelected: null,
    withinLastFiveYears: true,
    hasThirdPartyProof: false,
    sourceAuthority: "professional-respected",
    notes: "Well-known collector. On board of MoMA PS1.",
    recommenderName: "Patricia Chen",
    recommenderRole: "Collector, MoMA PS1 Board",
    recommenderIsSenior: true,
    recommenderIsUkBased: false,
    recommenderHasCollaborated: true,
    recommenderCollaborationProject: "Acquired 3 works, studio visits 2022-2024",
    recommenderHasCredentials: false,
    recommenderCanUseLetterhead: false,
  },
  {
    id: "ev-013",
    status: DONE,
    category: "cv-career-record",
    title: "Artist CV (3-page, tailored for GTV)",
    organisation: "Self",
    country: "United Kingdom",
    date: "2024-10",
    linkOrUpload: "https://example.com/cv.pdf",
    applicantNameVisible: true,
    applicantRoleClear: true,
    workTitleVisible: true,
    wasCuratedOrSelected: null,
    withinLastFiveYears: true,
    hasThirdPartyProof: false,
    sourceAuthority: "self-published",
    notes: "Chronological. Covers exhibitions, awards, residencies, collections.",
    ...REC_DEFAULTS,
  },
  {
    id: "ev-014",
    status: INTENT,
    category: "other-supporting",
    title: "Screenshot of personal website portfolio",
    organisation: "Personal website",
    country: "United Kingdom",
    date: "2024-10",
    linkOrUpload: "https://example.com/portfolio",
    applicantNameVisible: true,
    applicantRoleClear: true,
    workTitleVisible: true,
    wasCuratedOrSelected: null,
    withinLastFiveYears: true,
    hasThirdPartyProof: false,
    sourceAuthority: "self-published",
    notes: "Portfolio documentation. Not independently verifiable.",
    ...REC_DEFAULTS,
  },
];
